### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by jclega** [berthutapea/mern-employee-salary-management#2]

**Comment by jclega** [comment]
both frontend and backend running and connected to db...what is username pwd to login from frontend ui

**Comment by AffanButt** [comment]
both frontend and backend running and connected to db...what is username pwd to login from frontend ui

Same issue. Please provide the credentials as its not showing the NavBar

**Comment by jclega** [comment]
We stopped spending time on this and moved to orangehrm , much active support and community. thank you for the good work

**Comment by pruthvirathod** [comment]
I'm learning this project for college. So could you please have a guide on how to initialize the database and then what are the credentials for logging in pleaseee. Thanks!!
